### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by camrossi** [datacenter/aci-monitoring-stack#13]

**Comment by vaskomitrov** [comment]
Hi I implemented the stack on 3 fabrics and its working perfect. The only issue that i got is backup2graph failing with error . I tried to play with the constant.py but wasnt able to fix it. Any ideas how i can fix the relationship issue. Thanks a lot in advance 

Traceback (most recent call last):
  File "/app/backup2graph.py", line 456, in <module>
    process_backups(backups)
  File "/app/backup2graph.py", line 271, in process_backups
    create_non_pc_rel(data)
  File "/app/backup2graph.py", line 193, in create_non_pc_rel
    raise Exception ("Unknown Relationship: ", rel.ClassName)
Exception: ('Unknown Relationship: ', 'traceroutepRsTrEpIpSrc')

**Comment by camrossi** [comment]
@vaskomitrov What ACI version are you using ? Also would you mind opening a dedicated issue for this? I have an idea but would help me know what version you are testing.

**Comment by vaskomitrov** [comment]
Hi we have 3 clusters different versions but very closed . It happens on all of them .  Let me find out how to open dedicated issue :) 
Thanks a lot for your response and help. 

5.3(2e)
5.3(2b)
5.2(7g)
